version: 0.2

phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket bucketb2-test --output-template-file outputTemplate.yml
artifacts:
  files:
    - template.yaml